-- USER TABLE
CREATE TABLE IF NOT EXISTS Users(
	UserID INT NOT NULL PRIMARY KEY,
	Username VARCHAR(50),
	Password VARCHAR(255),
	RegisterAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    LastLogin DATE NOT NULL, 	-- TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
	Level INT NOT NULL,
	Coins INT NOT NULL
);
-- USER INDEX
CREATE INDEX IF NOT EXISTS idx_name ON Users(Username);


-- FRIENDSHIP TABLE
CREATE TABLE IF NOT EXISTS Friendship(
	SendID INT,
	RequestID INT,
	Status ENUM("pending", "accepted") DEFAULT "pending",
	CreateAt DATETIME DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (SendID, RequestID),
	FOREIGN KEY (SendID) REFERENCES Users(UserID),
	FOREIGN KEY (RequestID) REFERENCES Users(UserID)	
);
# FRIENDSHIP INDEX
CREATE INDEX IF NOT EXISTS idx_send_id ON Friendship(SendID);
CREATE INDEX IF NOT EXISTS idx_request_id ON Friendship(RequestID);